{
 "title": "File Storage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of requests per method",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(file_http_request_total{method=\"POST\"}[$__range])) by (method) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(file_http_request_total{method=\"GET\"}[$__range])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File upload response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (rate(file_upload_duration_seconds_sum[$__range])) / sum (rate(file_upload_duration_seconds_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Size",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,sort_desc(max_over_time(file_download_size_bytes_max[$__range])))",
     "legendFormat": "{{fileName}}"
    }
   ]
  }
 ]
}